### ISSUE TITLE
Problems Installing R Package

### ISSUE THREAD

**Issue by cavfan96** [sndmrc/BasketballAnalyzeR#1]
Team - I've been reading the book and want to work the solutions to gain a better feel for the capability. That said, I am struggling to install the package and have tried both from Github and CRAN. Here's the error I get:

Error: package or namespace load failed for ‘BasketballAnalyzeR’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/libs/Rcpp.so':
  dlopen(/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/libs/Rcpp.so, 6): Symbol not found: _EXTPTR_PTR
  Referenced from: /Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/libs/Rcpp.so
  Expected in: /Library/Frameworks/R.framework/Resources/lib/libR.dylib
 in /Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/libs/Rcpp.so
In addition: Warning message:
package ‘BasketballAnalyzeR’ was built under R version 4.0.2

**Comment by sndmrc** [comment]
Hi. Thank you for your email.
It seems a problem with the instalaltion of the package "Rcpp". 
Close all your R sessions, start a new one, and type 
install.packages("Rcpp").
If the installation runs with no errors, then try to install BasketballAnalyzeR.

In addition, please share the output of the following command:
sessionInfo()

Best regards.

**Comment by cavfan96** [comment]
Thank you for your reply, it is very welcome as I am still not able to load library(BasketballAnalyzeR).

I’m still getting pretty much the same error and have loaded both Rcpp and ggplot2 separately before trying BasketballAnalyzeR again.

Thanks, Paul


I get the following from sessionInfo():

R version 4.0.0 (2020-04-24)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.6

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] ggplot2_3.3.2

loaded via a namespace (and not attached):
 [1] rstudioapi_0.11    magrittr_1.5       tidyselect_1.1.0   munsell_0.5.0     
 [5] colorspace_1.4-1   R6_2.4.1           rlang_0.4.7        dplyr_1.0.1       
 [9] tools_4.0.0        grid_4.0.0         gtable_0.3.0       withr_2.2.0       
[13] ellipsis_0.3.1     tibble_3.0.3       lifecycle_0.2.0    crayon_1.3.4      
[17] purrr_0.3.4        RColorBrewer_1.1-2 vctrs_0.3.2        glue_1.4.1        
[21] compiler_4.0.0     pillar_1.4.6       generics_0.0.2     scales_1.1.1      
[25] pkgconfig_2.0.3

**Comment by sndmrc** [comment]
Hi. Try installing the latest version of R (do not uninstall the older R) and the library ggplot2. Then load the library and check if ggplot2 works (using  example(ggplot) ). After that, if all is OK, try installing BasketballAnalyzeR. Let me know.

**Comment by cavfan96** [comment]
I’m able to get it to run in R but not in RStudio for some reason.

Regardless, I’m very happy that I can now start learning how to use the package and run the code.

Thank you so much and if you happen to know anything RStudio related as to why it won’t work, feel free to share. I prefer it for some reason over R.

Thanks again - Paul
